POSTGRES_HOST: localhost
POSTGRES_DB: paqueteria
POSTGRES_USER: paqueteria
POSTGRES_PASSWORD: paqueteria

spring:
  profiles:
    active: "dev"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    hikari:
      pool-name: PaqueteriaPool
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  mail:
    host: "mail.kikisito.com"
    port: 587
    username: "ua-pracs@kikisito.com"
    password: "b$ATbJS$o3bajmGs5Ns*tmbmyhRRYRD9U7NAX1v^q@tI&QPejtz3Gc3RaAs9g312&W0LR#jPrHev%Gy5K@Qgf97XhsV#@a7YJEffqV198&$&@d&q^AcOey&Zz9DAhTa2"
    properties:
      mail:
        smtp:
          from: "ua-pracs@kikisito.com"
          auth: 'true'
          starttls:
            enable: 'true'

application:
  name: "Paquetería"
  host: http://localhost:8080
  security:
    jwt:
      secret-key: "IZfpeGlFl5xpPTiFe4BIrfePRlsN6eciiSqaFD3uP3AlABxb6KfxJ2ibRj7gCkSBG8iBevXi2GfLtYhveqiPTQ=="
      access-token:
        expiration: 86400000 # CAMBIAR
      refresh-token:
        expiration: 2592000000 # CAMBIAR
      password-reset-token:
        expiration: 3600000 # 1 hora